swagger: '2.0'
info:
  title: The Unified Portal API
  description: |
    The Universal Portal API that is supporting UI applications deployed with the portal backend.
  version: "1.2.0-b"
#host: ec-portal.run.aws-usw02-dev.ice.predix.io
schemes:
  - https
basePath: /
produces:
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    authorizationUrl: https://ec-oauth-sso.run.aws-usw02-dev.ice.predix.io/oauth/authorize
    tokenUrl: https://ec-oauth-sso.run.aws-usw02-dev.ice.predix.io/oauth/token
    description: OAuth 2.0 with Client Credentias Grant type
    scopes: []
    #  read: Grants read access
    #  write: Grants write access
    #  admin: Grants read and write access to administrative information
paths:
  /{rev}/api/{key}:
    post:
      summary: Create new key-value dataset
      description: |
        Create bew key-value pair dataset in the embedded DB.
      tags:
        - Dataset
      security:
        - OAuth2: []
      parameters: 
        - in: path
          name: rev
          default: v1.2beta
          description: |
            The revision for this SDC instance.
          required: true
          type: string
        - in: path
          name: key
          description: |
            The key for the key-value pair dataset.
          required: true
          type: string
        - in: body
          name: body
          description: |
            The value for the key-value pair dataset.
          required: true
          type: object
    put:
      tags:
        - Dataset
      
    get:
      summary: Get current scopes list
      description: |
        Get current scopes list which registered with SDC instance.
      tags:
        - Dataset
      security:
        - OAuth2: []
    
  /{rev}/reboot:
    post:
      summary: Restart the SDC instance
      description: |
        Restart the SDC instance immediately.
      tags:
        - System
      security:
        - OAuth2: []      
definitions:
  Token:
    type: object
    properties:
      access_token:
        type: string
        description: The access token value
      token_type:
        type: string
        enum: 
          - Bearer
        description: Type of the token is set to "Bearer"
      expires_in:
        type: integer
        format: int32
        description: The lifetime in seconds of the access token
  Error:
    type: object
    properties:
      error:
        type: string
        enum:
          - invalid_request
          - invalid_client
          - invalid_grant
          - unauthorized_client
          - unsupported_grant_type
      error_description:
        type: string
        description: Human-readable text providing additional information
      error_uri:
        type: string
        description: A URI identifying a human-readable web page with
         information about the error
